### ISSUE TITLE
Any plans for Sciter.JS port?

### ISSUE THREAD

**Issue by GirkovArpa** [MustafaHi/Sciter-MovableView#2]
I'm working on it, but having a hard time. 

The reason I don't want to use `window-role="caption"` is because it conflicts with css cursor properties.

**Comment by MustafaHi** [comment]
I do have plans to make a Sciter.JS port for this and [Sciter-Tray](https://github.com/MustafaHi/Sciter-Tray).
this week 🤞🏻 .

**Comment by MustafaHi** [comment]
I have made an [experimental port.](https://github.com/MustafaHi/Sciter-MovableView/blob/master/movableView.js)
there are few things to keep in mind:
1. It won't work well in uSciter unless you add `xoff += 55` and `yoff +=33` or something close.
This is because Sciter.JS don't have `x/yView`, and `x/yClient` (x/yRoot) are relative to the document rather than to the window.

2. The main issue right now is [mouse capture](https://sciter.com/forums/topic/mouse-capture-3/).
this cause an issue, when moving too fast or moving under (taskbar) it loss track, when it goes back you need to click again to send `mouseup` event.

Works pretty well nonetheless.

**Comment by GirkovArpa** [comment]
Fantastic!  You're right that it can't be dragged too fast, though.  On the bright side, I have discovered yet another advantage to your implementation over `role="window-caption"`:  It is not affected by "Aero Snap", so I can drag the window partly off the top of the screen without it being forceably snapped back to within the screen boundaries.
